### ISSUE TITLE
Error: Hydration failed because the initial UI does not match what was rendered on the server

### ISSUE THREAD

**Issue by subhendukundu** [mintlify/starter#1]
Got an error when navigated to `http://localhost:3000/introduction`.
Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.
See more info here: https://nextjs.org/docs/messages/react-hydration-error

**Comment by cursecodes** [comment]
+1

**Comment by tobias-mintlify** [comment]
The issues in the template have been fixed by this PR: https://github.com/mintlify/starter/pull/2

There are other ways of causing hydration errors. That work is being tracked in this issue: https://github.com/mintlify/mint/issues/258
