### ISSUE TITLE
[Docs UI]: Twitter Logo Update

### ISSUE THREAD

**Issue by ATREAY** [mintlify/starter#16]
## Short description of what should be added or improved
We must replace the current version of the Twitter logo in the footer of the documentation with the most up-to-date version.

## Screenshots
Please refer to the screenshot below:
![twitter icon](https://github.com/mintlify/starter/assets/66585295/36c1f905-0c14-4a26-b321-964d8c395519)

## Anything else?
**I would like to work on this issue if it's good to go!**

**Comment by ATREAY** [comment]
Hey @handotdev, can you confirm if this issue is valid? It could potentially impact all the documents that use Mintlify.

**Comment by Faizan711** [comment]
Is this issue still open I would like to work on it.

**Comment by SAD0XER** [comment]
@handotdev @hahnbeelee @ghoshnirmalya, I think this issue is **resolved**, refer the screenshot below.
It is the landing page of [`mintlify`](https://mintlify.com/).

![image](https://github.com/mintlify/starter/assets/79737447/b7672393-60e7-4876-80b1-c654b392812e)
