### ISSUE TITLE
Unable to populate a default value for an API endpoint.

### ISSUE THREAD

**Issue by bfeif** [mintlify/starter#18]
I've tried setting any/all of the fields `default`, `initialValue`, and `placeHolder`, and none of them seem to do it, for neither `header` `ParamField`'s nor `query` `ParamField`'s. Any suggestions?

**Comment by fmerian** [comment]
Hi @bfeif, sorry to read this.

If this still makes sense, could you please send us an email at [support@mintlify.com](mailto:support@mintlify.com) so I can assign it to the right team member? We'll reply shortly. 

Thanks!
