### ISSUE TITLE
[i18n] How to add a multilingual document?

### ISSUE THREAD

**Issue by azhengyongqin** [mintlify/starter#19]
### How to add a multilingual document?
like this: 
<img width="694" alt="image" src="https://github.com/mintlify/docs/assets/18138282/d92c47fa-aa2e-4db1-a923-b1e5ff644d9f">

**eg:** 
English: https://mintlify.com/en/docs/quickstart 
Chinese: https://mintlify.com/zh/docs/quickstart

**Comment by sebastianjnuwu** [comment]
Any news on when it will be implemented?

**Comment by teovillanueva** [comment]
We would love to have this feature 🙌🏻

**Comment by fmerian** [comment]
Hi @azhengyongqin, sorry for my late reply here, and thanks for the idea!

FYI one workaround is using `Versioning` — a feature we recently introduced:

Add this to your `mint.json` file: 
```
"versions": ["English", "Chinese"]
```

`English` and `Chinese` are the names of your versions. Take [Anthropic's docs](https://docs.anthropic.com/en/docs/initial-setup), for example.

You can learn more about `Versioning` [here](https://mintlify.com/docs/settings/versioning).

Hope it helps! cc @sebastianjnuwu @teovillanueva for the record

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/user-attachments/assets/73c388f9-ba6b-4780-9232-157e3e85b715">
  <source media="(prefers-color-scheme: light)" srcset="https://github.com/user-attachments/assets/a402384f-5502-4090-a43d-cac538d9e333">
  <img alt="Anthropic's Docs" src="https://github.com/user-attachments/assets/a402384f-5502-4090-a43d-cac538d9e333">
</picture>
