### ISSUE TITLE
link a pdf in mintlify

### ISSUE THREAD

**Issue by rafipiccolo** [mintlify/starter#26]
I'd like to link to a client api in my own documentation.
The client does not provide a url for this pdf. it only mails me thoses pdfs...

I would like to write this and simply put the file in the repo:
```
[API-client.pdf](/images/API-client.pdf)
```

I tried many paths but it all fail.
I tried iframe syntax too.

could you allow it ?

**Comment by fmerian** [comment]
Bonjour @rafipiccolo, great suggestion!

While this is not possible right now, could you please [submit your idea here](https://feedback.mintlify.com/roadmap) so we can prioritize it? 

Thanks!

**Comment by sebastianpikand** [comment]
please add this as a feature
