### ISSUE TITLE
Add Custom Dependencies

### ISSUE THREAD

**Issue by ChurroC** [mintlify/starter#32]
Currently I'm trying to add @codesandbox/sandpack-react to have live editing for users. I also wanted to add chart.js to show custom data and info.
But I can't seem to figure out how to add custom dependencies. Especially when I'm trying to use these libraries. Because I know you can use react components but I'm not sure how to add dependencies and use them.

**Comment by fmerian** [comment]
Hi @ChurroC, great suggestion!

Could you please [submit this idea here](https://feedback.mintlify.com/roadmap) so we can prioritize it?

Thanks!
