### ISSUE TITLE
Error when referencing component schema from multiple OpenAPI file in response

### ISSUE THREAD

**Issue by mayank-ekacare** [mintlify/starter#40]
**Description**
I'm encountering an issue when trying to reference a schema from one OpenAPI specification (YAML file) into another. The reference does not seem to resolve correctly, and I receive the following error:

**Error Message:**

Error: no matching OpenAPI operation object found with path "/example" and method "get"

Steps to Reproduce
Here are the steps to reproduce the issue:

service.yaml
```
openapi: 3.0.0
info:
  title: service
  version: 1.0.0
components:
  schemas:
    ExampleModel:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
```

api.yaml
```
openapi: 3.0.0
info:
  title: API 2
  version: 1.0.0
paths:
  /example:
    get:
      summary: Using service schema in API 2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: './service.yaml#/components/schemas/ExampleModel'
```

**Expected Behavior**
I expect that the reference to ExampleModel from service.yaml should resolve correctly, and I should be able to use it in the response of the GET /example path in api.yaml.

**Comment by fmerian** [comment]
Hi @mayank-ekacare, thanks for the report!

Could you please send us an email at [support@mintlify.com](mailto:support@mintlify.com) so we can prioritize it? We'll reply shortly. Thanks!
