### ISSUE TITLE
Can't run dev command

### ISSUE THREAD

**Issue by jinrenjie** [mintlify/starter#5]
Output:
```bash
$ mintlify dev
✖ Running mintlify dev for the first time requires an internet connection.
```

**Comment by liuhuapiaoyuan** [comment]
have same error

**Comment by smyja** [comment]
same error

**Comment by alexcai88** [comment]
same error

**Comment by ahmedmansoor** [comment]
no fix, anyone?

**Comment by jinrenjie** [comment]
The problem may be that your current network environment cannot request `mint-releases.b-cdn.net`. You can try using a proxy.

**Comment by ming535** [comment]
Can you add more retries for this command line? I can access https://mint-releases.b-cdn.net/mint-0.0.613.tar.gz via my browser and setup my proxy properly, but the command line still fails. It seems that it is retrying for 2 times? Can you add more retries?

`retry: {
      limit: 2,
      methods: [ 'GET', 'PUT', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE' ],
      statusCodes: [
        408, 413, 429, 500,
        502, 503, 504, 521,
        522, 524
      ],
      errorCodes: [
        'ETIMEDOUT',
        'ECONNRESET',
        'EADDRINUSE',
        'ECONNREFUSED',
        'EPIPE',
        'ENOTFOUND',
        'ENETUNREACH',
        'EAI_AGAIN'
      ],
      maxRetryAfter: undefined,
      calculateDelay: [Function: calculateDelay],
      backoffLimit: Infinity,
      noise: 100
    },`

**Comment by wyrover** [comment]
同样的问题，通过浏览器下载后，修改这个文件 `mintlify\node_modules\@mintlify\previewing\dist\local-preview\index.js`，直接注释掉这行 `//yield pipeline(got.stream(TAR_URL), fse.createWriteStream(TAR_PATH));`    不然他每次运行都会下载。
