### ISSUE TITLE
Card with image not working

### ISSUE THREAD

**Issue by quangas** [mintlify/starter#6]
Any idea why you cannot use the image tag inside a Card? It doesn't seem to render. Why don't you show an example of this in the documentation?

```
<Card
    title="Hello world"
    href="https://mintlify.com/docs/quickstart"
    image="/images/hello.png"
  >
    Once upon a time
  </Card>
```

**Comment by fmerian** [comment]
Hello there! Thanks for the report.

You're spot on and we're currently working on fixing it. In the meantime, check out [this repo](https://github.com/mintlify/themes/tree/main/quill) that includes a workaround using `Snippets` ([demo](https://starter-quill.mintlify.app/introduction)).

Example:

``` mdx
export const HeroCard = ({ img, title, description, href }) => {
  return (
    <a className="border-b pb-8 cursor-pointer border-gray-500 dark:border-gray-800 hover:!border-primary dark:hover:!border-primary-light" href={href}>
      <img src={img} />
      <h1 className="mt-4 font-semibold text-gray-900 dark:text-white">{title}</h1>
      <h2 className="mt-1 text-gray-600 dark:text-gray-400 text-sm leading-6">{description}</h2>
    </a>
  )
}
```

Hope it helps!
